# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4633b7e8b0f193038eb88856465031421812fd1132bf6a327e7cacc04dd12f7ffab03f73faeffa6fce317b45f71ee551e64364d55442261a27bad5641448f4a0

test:
  secret_key_base: a3ef0483e287b14d5c3a5aa9e7891c7b23b625ade354bbc8db3c7b0785860c1c1f94a3162a3d8aee0ca06f0b74518b629f5b3fb2b092895d5b2c0201905f3ed5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
